name: Prepare images

on:
  push:
    branches:
      - staging
      - master
  workflow_run:
    workflows: [Tests]
    types:
      - completed
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  on-success:
    name: Builds and pushes image(s)
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: Set up environment variables
        run: |
          echo "IMAGES_PREFIX=${{ secrets.DOCKERHUB_USERNAME }}/sentry-" >> $GITHUB_ENV
          echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      -
        name: Build Docker images
        uses: docker/bake-action@v5
        with:
          pull: true
          load: true
          push: true
          files: |
            compose.yml
            compose.prod.yml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}} 
            *.cache-from=type=gha,scope=refs/heads/master
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
